repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length, "120", --exclude, "./scikit-learn/*"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--skip, "./scikit-learn/*"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--exclude, "./scikit-learn/*"]


  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --recursive, --remove-unused-variables, --in-place, --exclude, "./scikit-learn/*"]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args:
          [
            "-rn",
            "--rcfile=pylintrc",
            "--ignore-patterns=.*_test.py,test_.*.py,^scikit-learn/,^scikit-learn/.*$,^scikit_longitudinal/tests/.*$",
          ]
