[project]
name = "Scikit-longitudinal"
version = "0.0.2"
description = "Scikit-longitudinal, an open-source Python lib for longitudinal data analysis, builds on Scikit-learn's foundation. It offers specialized tools to tackle challenges of repeated measures data, ideal for researchers, data scientists, & analysts."
authors = [
    {name = "Simon Provost",email = "sgp28@kent.ac.uk"},
]
dependencies = [
    "pandas<2.0.0,>=1.5.3",
    "matplotlib<4.0.0,>=3.7.0",
    "jupyter<2.0.0,>=1.0.0",
    "overrides<8.0.0,>=7.3.1",
    "ray<3.0.0,>=2.3.1",
    "statsmodels<1.0.0,>=0.14.0",
    "numpy>=1.20",
    "graphviz<1.0.0,>=0.20.1",
    "autoflake<3.0.0,>=2.1.1",
    "docformatter[tomli]<2.0.0,>=1.6.4",
    "arff<1.0,>=0.9",
    "threadpoolctl<4.0.0,>=3.1.0",
    "configspace<1.0.0,>=0.7.1",
    "smac<3.0.0,>=2.0.2",
    "deep-forest>=0.1.7",
    "Cython==0.29.33",
    "scipy>=1.5.0",
    "pytest-cov>=4.0.0",
    "flake8-docstrings>=1.7.0",
    "pydocstyle>=6.3.0",
    "genbadge>=1.1.0",
    "flake8>=6.0.0",
    "pylint>=2.17.1",
    "isort>=5.12.0",
    "autopep8>=2.0.2",
    "black>=23.10.1",
    "pre-commit>=3.2.0",
    "autoflake>=2.1.1",
    "docformatter>=1.6.4",
    "rich>=13.6.0",
    "stopit>=1.1.2",
    "pdoc3>=0.10.0",
]
requires-python = ">=3.8.1,<3.10"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
_.env_file = ".env"

# Project setup (Note: This has only been tested on Linux && OSX)
_use_python39 = {shell = "pdm use -f python3.9"}
_create_env = {shell = "pdm venv create --with-pip 3.9 --force"}
_set_env_var = {shell = "echo 'could you please run `export PDM_IN_ENV=in-project`'"}
_activate_env = {cmd = "echo 'could you please activate the environment via `eval $(pdm venv activate (dollar-sign)PDM_IN_ENV)`'"}
setup_project = {composite = ["_use_python39", "_create_env", "_set_env_var", "_activate_env"]}
remove_env = { cmd = "pdm venv remove ${PDM_IN_ENV}" }
_clean_project = {cmd = "echo could you please deactivate the environment via `conda deactivate` then run `pdm run remove_env`"}
clean = {composite = ["_check_pdm_vars", "_clean_project"]}
_install_deps = { cmd = "pdm install --venv ${PDM_IN_ENV}" }
_build_scikit_tree = {shell = "cd ./scikit-learn/ && pip install --verbose --no-build-isolation --editable ./ && cd .."}
_check_env = {call = "scripts.pdm.pdm_pre_install:check_environment_variables"}
_check_pdm_vars = {call = "scripts.pdm.pdm_pre_install:check_pdm_variables"}
_risky_clean = { shell = "rm -rf pdm.lock __pypackages__" }
install_project = {composite = ["_check_pdm_vars", "_check_env", "_install_deps", "_build_scikit_tree"]}
view_env = {cmd = "pdm venv list"}

# Testing and linting (Note: This has only been tested on Linux && OSX)
tests = {cmd = "pytest scikit_longitudinal/ --cov=./ --cov-report=html --cov-config=.coveragerc --cov-report=html:htmlcov/scikit_longitudinal -s -vv --capture=no"}
clean_cache = {shell = "rm -rf htmlcov .pytest_cache .*_cache && find . -type d -name '__pycache__' -exec rm -r {} +"}
isort = {cmd = "isort --skip=scikit-learn scikit_longitudinal"}
black = {cmd = "black --line-length 120 --preview --exclude=./scikit-learn/* scikit_longitudinal"}
flake8 = {cmd = "flake8 --exclude=./scikit-learn/* scikit_longitudinal"}
autoflake = {cmd = "autoflake --in-place --remove-all-unused-imports --recursive --exclude=./scikit-learn/* scikit_longitudinal"}
pylint = {cmd = "pylint --rcfile=pylintrc scikit_longitudinal/"}
precommit = {shell = "git ls-files -- 'scikit_longitudinal/*.py' | xargs pre-commit run --files"}
autopep8 = {cmd = "autopep8 --in-place --aggressive --aggressive --max-line-length 120 --recursive --exclude=./scikit-learn/* scikit_longitudinal"}
docformatter = {cmd = "docformatter --in-place --recursive --wrap-summaries 120 --wrap-descriptions 120 --blank --make-summary-multi-line --exclude=./scikit-learn/ scikit_longitudinal"}
lint = {composite = ["flake8", "pylint"]}
format = {composite = ["isort", "autopep8", "black", "autoflake", "docformatter"]}
lint_format_tests = {composite = ["format", "lint", "tests"]}

#Documentation
docs = {shell = "rm -rf docs && pdoc --html --output-dir docs scikit_longitudinal/ --force --template-dir pdoc/template/ && mv docs/scikit_longitudinal/* docs/ && rm -rf docs/scikit_longitudinal"}

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | scikit-learn
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.yapfignore]
ignore_patterns = [
  "scikit-learn/**/*.py",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool]
[tool.pdm]
[tool.pdm.build]
includes = ["scikit_longitudinal"]
