name: ci-tests

on:
  pull_request:
    branches:
      - main

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.9 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout this repository
        uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.9
          architecture: x64
          prerelease: false
          enable-pep582: true

      - name: Install dependencies from pdm.lock
        run: |
          pdm install

      - name: Run tests
        run: pdm run tests
